import * as S from './styled';

const TableSearch = () => {
  return (
    <>
      <S.SubTitle>Busca realizadas</S.SubTitle>
      <S.Table>
        <thead>
          <S.Tr>
            <S.Th>Hashtag</S.Th>
            <S.Th>Data</S.Th>
            <S.Th>Hora</S.Th>
          </S.Tr>
        </thead>
        <S.Tbody>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
          <S.Tr>
            <S.Td>#hashtagname</S.Td>
            <S.Td>25/02</S.Td>
            <S.Td>09:30</S.Td>
          </S.Tr>
        </S.Tbody>
      </S.Table>
    </>
  );
};
export default TableSearch;
